Containerfile: Install osbuild from COPR to pull a fix for the loop bug
Builds are failing on certain systems on:
AttributeError: 'Loop' object has no attribute 'fd'
osbuild.host.RemoteError: FileNotFoundError: [Errno 2] No such file or
directory: 'loop1'

This happens because /dev in a container is a statically created tmpfs. Thus,
when a new loop device is allocated, it doesn't appear in the container.
A newer version of osbuild fixes that by always making sure that the loop
device exists (by simply calling `mknod`). Pull the fix from COPR to unblock
us, instead of waiting for the fix to flow into stable Fedora.

`dnf copr enable` requires `dnf-plugins-core` that's not installed by default.
Let's just use a static .repo file instead, it feels a tad bit simpler.