image: only allow tweaks to /, /boot for now
The "images" library does not support custom mount points for
bootc based images just yet. The reason is that images will
generate an osbuild manifest that contains all the "mounts"
for the generated disk. This means that with an extra partition
like `/var/log` this is visible for the "bootc install-to-filesystem"
stage. And that will trip up bootc because it validates the content
of the target directory. Example error with `/var/log` as a custom
mount point:
```
...
Installing image: docker://quay.io/centos-bootc/centos-bootc:stream9
ERROR Installing to filesystem: Verifying empty rootfs: Non-empty root filesystem; found "var"
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.bootc.install-to-filesystem", line 53, in <module>
    r = main(args["options"], args["inputs"], args["paths"])
  File "/run/osbuild/bin/org.osbuild.bootc.install-to-filesystem", line 48, in main
    subprocess.run(pargs, env=env, check=True)
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bootc', 'install', 'to-filesystem', '--source-imgref', 'containers-storage:[overlay@/run/osbuild/containers/storage+/run/containers/storage]3b612dd1fae2437c00ae3187d0e63daa7a94711560fb1712389edd4121668c96', '--skip-fetch-check', '--generic-image', '--karg', 'rw', '--karg', 'console=tty0', '--karg', 'console=ttyS0', '--karg', 'systemd.journald.forward_to_console=1', '--target-imgref', 'quay.io/centos-bootc/centos-bootc:stream9', '/run/osbuild/mounts']' returned non-zero exit status 1.
```

So AFAICT "images" need sto be changed so that:

1. The "install-to-filesystem" stage only takes the "essential" mounts (/, /boot/, /boot/efi)
2. After "install-to-filesystem" ran we need a "org.osbuild.mkdir" stage for the extra mount points that also only mounts the "essential" mounts

As a first step on the journy this commit limits customizations to
"/" and "/boot" which is already very useful as many people have
asked for precisely those.