Support root-less containers with --in-vm
This updates to the latest image-builder-cli, adding support for
rootless container use
(https://github.com/osbuild/image-builder-cli/pull/445).

It also updates the use of related APIs to pass runInVm options where
needed.

With this, I was able to run a rootless bc-i-b conversion.

There is one problem, which is that if you mount
`~/.local/share/containers/storage` on the host to
`/var/lib/containers/storage` in the container, podman will complain
with:

```
Error: database static dir "~/.local/share/containers/storage/libpod"
does not match our static dir "/var/lib/containers/storage/libpod":
database configuration mismatch
```

Additionally, if you pass the host `/var/lib/containers/storage` into
the rootless container you will get read permission errors.

There are two workarounds for this. Either you can use e.g. skopeo to
copy the bootc container to a separate (non-root) container storage
directory and mount that, or you can cover the `db.sql` file in the
storage directory to make podman not print the error.

Neither of these are super clean, and we should try to figure out a
better solution, but for now I was at least able to run a complete
image build using the "cover db" apprach like this:

```
$ touch /tmp/foo
$ podman run --rm --security-opt label=type:unconfined_t -ti --privileged \
  --network=none -v $PWD/output:/output \
  -v ~/.local/share/containers/storage:/var/lib/containers/storage \
  -v /tmp/foo:/var/lib/containers/storage/db.sql \
  localhost/bootc-image-builder  --in-vm \
  --rootfs ext4 --type raw \
  quay.io/fedora/fedora-bootc:43
```